# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=55)),
                ('lastName', models.CharField(max_length=55)),
                ('addrLine1', models.CharField(max_length=100)),
                ('addrLine2', models.CharField(max_length=100, verbose_name=b'')),
                ('postCode', models.CharField(max_length=20, verbose_name=b'')),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=120, verbose_name=b'')),
                ('website', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmmiici.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=55)),
                ('lastName', models.CharField(max_length=55)),
                ('addrLine1', models.CharField(max_length=100)),
                ('addrLine2', models.CharField(max_length=100, verbose_name=b'')),
                ('postCode', models.CharField(max_length=20, verbose_name=b'')),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=120, verbose_name=b'')),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('doctors', models.ManyToManyField(through='bmmiici.DoctorSpecialization', to='bmmiici.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctorspecialization',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmmiici.Specialization'),
        ),
    ]
