# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmiici', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specializations',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
    ]
